version: '2.1'

services:
  postgres:
    extends:
      file: ../docker-common.yml
      service: postgres

  redis:
    extends:
      file: ../docker-common.yml
      service: redis

  smart_backend:
    extends:
      file: ../docker-common.yml
      service: smart_backend
    build: ../../backend/
    image: rubentea16/smart_backend:latest
    depends_on:
      - postgres
      - redis

  smart_frontend:
    extends:
      file: ../docker-common.yml
      service: smart_frontend
    build: ../../frontend/
    image: rubentea16/smart_frontend:latest
    command: node_modules/.bin/webpack --watch

  celery_worker:
    extends:
      file: ../docker-common.yml
      service: celery_worker
    build: ../../backend/
    image: rubentea16/smart_backend:latest
    depends_on:
      - postgres
      - redis
      - smart_backend

volumes:
  smart_pgdata:
    external:
      name: vol_smart_pgdata
  smart_data:
    external:
      name: vol_smart_data
